services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: Auctions
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
